/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package administrador;

import java.awt.Color;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import sql.Conexion;

/**
 *
 * @author carto
 */
public class GuardarEst extends javax.swing.JFrame {

    /**
     * Creates new form GuardarEst
     */
    private alumno.Alumno est;
    
    public GuardarEst() {
        this.setUndecorated(true);
        initComponents();
        asignarTextoLbl();        
    }
    
    public GuardarEst(alumno.Alumno est){
        this.setUndecorated(true);
        initComponents();  
        this.est=est;
        asignarTextoLbl();
    }
    
    private void asignarTextoLbl(){
        lblNombre.setText(est.getNOMBRE());
        lblCIF.setText(est.getCIF() + "");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblCIF = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        txtPassword = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        btnGuardar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(500, 270));
        setPreferredSize(new java.awt.Dimension(500, 270));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(500, 260));
        jPanel1.setPreferredSize(new java.awt.Dimension(500, 260));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagesLogin/cerrar.png"))); // NOI18N
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 10, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagesAdmin/RectanguloPanelGuardar.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        jLabel2.setText("CIF: ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 60, 40, 30));

        lblCIF.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        jPanel1.add(lblCIF, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 60, 60, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        jLabel4.setText("Nombre:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, 30));

        lblNombre.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        jPanel1.add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 280, 30));

        txtCorreo.setFont(new java.awt.Font("Segoe UI Semibold", 0, 15)); // NOI18N
        txtCorreo.setForeground(new java.awt.Color(222, 221, 221));
        txtCorreo.setText("Correo Electronico");
        txtCorreo.setBorder(null);
        txtCorreo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCorreoFocusLost(evt);
            }
        });
        txtCorreo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtCorreoMouseClicked(evt);
            }
        });
        jPanel1.add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 270, 40));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 270, 10));

        txtPassword.setFont(new java.awt.Font("Segoe UI Semibold", 0, 15)); // NOI18N
        txtPassword.setForeground(new java.awt.Color(222, 221, 221));
        txtPassword.setText("Contraseña");
        txtPassword.setBorder(null);
        txtPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPasswordFocusLost(evt);
            }
        });
        txtPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtPasswordMouseClicked(evt);
            }
        });
        jPanel1.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 270, 40));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 270, 10));

        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagesAdmin/btnCrearEstudiante.png"))); // NOI18N
        btnGuardar.setBorder(null);
        btnGuardar.setBorderPainted(false);
        btnGuardar.setContentAreaFilled(false);
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jPanel1.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 160, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 260));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        boolean facultad=false, alumno=false;
        
        if((!txtCorreo.getText().equals("")) && (!txtPassword.getText().equals(""))){
            est.setEMAIL_INSTITUCION(txtCorreo.getText());
            est.setCONTRASENA_SISTEMA(txtPassword.getText());
            
            try {
                String consulta = "INSERT INTO PERSONAL VALUES("+est.getCIF()+",'"+est.getCOD_FACULTAD()+"','"+est.getNOMBRE()+"','"+est.getCEDULA()+ "','" + est.getDIRECCION()
                        + "','" + est.getFECHA_NACIMIENTO() + "','" + est.getEMAIL_INSTITUCION() + "','" + est.getCONTRASENA_SISTEMA()+"')";
                
                PreparedStatement sql = Conexion.getConnection().prepareStatement(consulta);
                
                sql.executeUpdate();
                facultad=true;
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, ex.toString());
            }
            
            try {
                String consulta2 = "INSERT INTO ESTUDIANTE VALUES(" + est.getCIF() + "," + est.getID_CARRERA() + ",'" + est.getFECHA_INGRESO() + "')";
                PreparedStatement sql = Conexion.getConnection().prepareStatement(consulta2);
                 
                sql.executeUpdate();
                alumno=true;
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, ex.toString());
            }
            
            if(alumno==true  &&  facultad==true){
                JOptionPane.showMessageDialog(this, "El alumno " + est.getNOMBRE() + " con CIF: " + est.getCIF() + ", ha sido creado correctamente");
                this.dispose();
            }else{
                JOptionPane.showMessageDialog(null, "Error, no se pudo crear el alumno");
            }
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void txtCorreoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCorreoMouseClicked
        if(txtCorreo.getText().equals("Correo Electronico")){
            txtCorreo.setText("");
            txtCorreo.setForeground(new Color(56,51,51));
        }
    }//GEN-LAST:event_txtCorreoMouseClicked

    private void txtCorreoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCorreoFocusLost
        if(txtCorreo.getText().equals("")){
            txtCorreo.setText("Correo Electronico");
            txtCorreo.setForeground(new Color(222,221,221));
        }
    }//GEN-LAST:event_txtCorreoFocusLost

    private void txtPasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPasswordMouseClicked
        if(txtPassword.getText().equals("Contraseña")){
            txtPassword.setText("");
            txtPassword.setForeground(new Color(56,51,51));
        }
    }//GEN-LAST:event_txtPasswordMouseClicked

    private void txtPasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPasswordFocusLost
        if(txtPassword.getText().equals("")){
            txtPassword.setText("Contraseña");
            txtPassword.setForeground(new Color(222,221,221));
        }
    }//GEN-LAST:event_txtPasswordFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuardarEst.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuardarEst.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuardarEst.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuardarEst.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GuardarEst().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblCIF;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtPassword;
    // End of variables declaration//GEN-END:variables
}
