/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package administrador;

import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import sql.Conexion;

/**
 *
 * @author carto
 */
public class SeleccionarPensum extends javax.swing.JFrame {

    public int id_pensum=-2;
    
    public SeleccionarPensum() {
        initComponents();
        adminPerfil.agregarFacultades(cmbFacultades);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        cmbFacultades = new javax.swing.JComboBox<>();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtPensum = new javax.swing.JTable();
        btnSeleccionarS = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(500, 260));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(500, 260));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagesLogin/cerrar.png"))); // NOI18N
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setFocusable(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 10, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagesAdmin/RectanguloPanelGuardar.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        cmbFacultades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbFacultadesActionPerformed(evt);
            }
        });
        jPanel1.add(cmbFacultades, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 190, -1));

        jTextField1.setText("jTextField1");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 90, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Facultad");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jtPensum.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID_Pensum", "Nombre carrera"
            }
        ));
        jtPensum.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtPensumMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtPensum);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 280, 120));

        btnSeleccionarS.setText("Seleccionar registro");
        btnSeleccionarS.setEnabled(false);
        btnSeleccionarS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionarSActionPerformed(evt);
            }
        });
        jPanel1.add(btnSeleccionarS, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 170, -1, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 260));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        adminPerfil.setTextBtn("");
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cmbFacultadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbFacultadesActionPerformed
        if(cmbFacultades.getSelectedIndex()!=0){
            consultaTabla(cmbFacultades.getSelectedItem().toString());
        }else{
            jtPensum.removeAll();
        }
    }//GEN-LAST:event_cmbFacultadesActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void btnSeleccionarSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionarSActionPerformed
        
        int row = jtPensum.getSelectedRow();

        id_pensum = Integer.parseInt(jtPensum.getModel().getValueAt(row, 0).toString());
        JOptionPane.showMessageDialog(null, "Registro seleccionado correctamente");
        adminPerfil.setTextBtn(id_pensum+"");
        this.dispose();

    }//GEN-LAST:event_btnSeleccionarSActionPerformed

    private void jtPensumMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtPensumMouseClicked
        if(jtPensum.getSelectionModel().isSelectionEmpty()){
            btnSeleccionarS.setEnabled(false);
        }else{
            btnSeleccionarS.setEnabled(true);
        }
    }//GEN-LAST:event_jtPensumMouseClicked

    private void consultaTabla(String COD_Facultad){
        try {
            DefaultTableModel model = new DefaultTableModel();
            jtPensum.setModel(model);
            
            Statement sql = Conexion.getConnection().createStatement();
            
            String consulta = "SELECT P.ID_PENSUM, C.NOMBRE_CARRERA FROM CARRERA AS C INNER JOIN PENSUM AS P ON C.ID_CARRERA=P.ID_CARRERA WHERE COD_FACULTAD='" + COD_Facultad + "'";
                     
            ResultSet resultado = sql.executeQuery(consulta);
            
            ResultSetMetaData rsMd = resultado.getMetaData();
            int cantCol = rsMd.getColumnCount();
            
            model.addColumn("ID_Pensum");
            model.addColumn("Nombre carrera");
            
            while(resultado.next()){
                Object[] filas = new Object[cantCol];
                for(int i=0;i<cantCol;i++){
                    filas[i] = resultado.getObject(i+1);
                    
                }
                model.addRow(filas);
            }
            
        } catch (Exception e) {
            System.out.println(e.toString());
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SeleccionarPensum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SeleccionarPensum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SeleccionarPensum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SeleccionarPensum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SeleccionarPensum().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSeleccionarS;
    private javax.swing.JComboBox<String> cmbFacultades;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTable jtPensum;
    // End of variables declaration//GEN-END:variables
}
